"""empty message

Revision ID: 6df4334ee02c
Revises: 
Create Date: 2019-12-11 14:34:09.624215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6df4334ee02c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('departmentID', sa.CHAR(length=3), nullable=False),
    sa.Column('departmentName', sa.CHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('departmentID')
    )
    op.create_table('patient',
    sa.Column('patientID', sa.CHAR(length=4), nullable=False),
    sa.Column('name', sa.CHAR(length=20), nullable=True),
    sa.Column('gender', sa.CHAR(length=1), nullable=True),
    sa.Column('birthDay', sa.DATE(), nullable=True),
    sa.Column('phoneNumber', sa.CHAR(length=11), nullable=True),
    sa.Column('address', sa.CHAR(length=20), nullable=True),
    sa.Column('password', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('patientID')
    )
    op.create_table('medicalstaff',
    sa.Column('StaffID', sa.CHAR(length=4), nullable=False),
    sa.Column('name', sa.CHAR(length=20), nullable=True),
    sa.Column('gender', sa.CHAR(length=1), nullable=True),
    sa.Column('department_ID', sa.CHAR(length=3), nullable=True),
    sa.Column('entryDay', sa.DATE(), nullable=True),
    sa.Column('retirementDate', sa.DATE(), nullable=True),
    sa.Column('phoneNumber', sa.CHAR(length=11), nullable=True),
    sa.Column('officeNo', sa.CHAR(length=10), nullable=True),
    sa.Column('position', sa.CHAR(length=20), nullable=True),
    sa.Column('email', sa.CHAR(length=20), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('password', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['department_ID'], ['department.departmentID'], ),
    sa.PrimaryKeyConstraint('StaffID')
    )
    op.create_table('nursing',
    sa.Column('patienID', sa.CHAR(length=4), nullable=False),
    sa.Column('nurseID', sa.CHAR(length=4), nullable=False),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('conditionDesc', sa.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['nurseID'], ['medicalstaff.StaffID'], ),
    sa.ForeignKeyConstraint(['patienID'], ['patient.patientID'], ),
    sa.PrimaryKeyConstraint('patienID', 'nurseID')
    )
    op.create_table('schedule',
    sa.Column('staff_ID', sa.CHAR(length=4), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('timeInterval8', sa.CHAR(length=1), nullable=True),
    sa.Column('timeInterval9', sa.CHAR(length=1), nullable=True),
    sa.Column('timeInterval10', sa.CHAR(length=1), nullable=True),
    sa.Column('timeInterval11', sa.CHAR(length=1), nullable=True),
    sa.Column('timeInterval14', sa.CHAR(length=1), nullable=True),
    sa.Column('timeInterval15', sa.CHAR(length=1), nullable=True),
    sa.Column('timeInterval16', sa.CHAR(length=1), nullable=True),
    sa.Column('timeInterval17', sa.CHAR(length=1), nullable=True),
    sa.ForeignKeyConstraint(['staff_ID'], ['medicalstaff.StaffID'], ),
    sa.PrimaryKeyConstraint('staff_ID', 'date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule')
    op.drop_table('nursing')
    op.drop_table('medicalstaff')
    op.drop_table('patient')
    op.drop_table('department')
    # ### end Alembic commands ###
