"""empty message

Revision ID: a122b96c985f
Revises: 6df4334ee02c
Create Date: 2019-12-11 14:34:28.246198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a122b96c985f'
down_revision = '6df4334ee02c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('doctor_ID', sa.CHAR(length=4), nullable=True))
    op.add_column('department', sa.Column('nurse_ID', sa.CHAR(length=4), nullable=True))
    op.create_foreign_key(None, 'department', 'medicalstaff', ['nurse_ID'], ['StaffID'])
    op.create_foreign_key(None, 'department', 'medicalstaff', ['doctor_ID'], ['StaffID'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'department', type_='foreignkey')
    op.drop_constraint(None, 'department', type_='foreignkey')
    op.drop_column('department', 'nurse_ID')
    op.drop_column('department', 'doctor_ID')
    # ### end Alembic commands ###
