"""empty message

Revision ID: a786ed0c049f
Revises: 1d65f4e3bbb9
Create Date: 2019-12-11 14:54:58.910125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a786ed0c049f'
down_revision = '1d65f4e3bbb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('hospitalization_ibfk_3', 'hospitalization', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('hospitalization_ibfk_3', 'hospitalization', 'medicalstaff', ['nurse_ID'], ['StaffID'])
    # ### end Alembic commands ###
