"""empty message

Revision ID: d1c693f8649b
Revises: faba045124d2
Create Date: 2019-12-11 14:37:28.958447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1c693f8649b'
down_revision = 'faba045124d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bed',
    sa.Column('bedNo', sa.CHAR(length=4), nullable=False),
    sa.Column('ward_No', sa.CHAR(length=4), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ward_No'], ['ward.wardNo'], ),
    sa.PrimaryKeyConstraint('bedNo')
    )
    op.create_table('hospitalization',
    sa.Column('bedNo', sa.CHAR(length=4), nullable=False),
    sa.Column('patient_ID', sa.CHAR(length=4), nullable=False),
    sa.Column('doctor_ID', sa.CHAR(length=4), nullable=True),
    sa.Column('nurse_ID', sa.CHAR(length=4), nullable=True),
    sa.Column('startDate', sa.DATE(), nullable=True),
    sa.Column('endDate', sa.DATE(), nullable=True),
    sa.Column('transferHospital', sa.CHAR(length=1), nullable=True),
    sa.ForeignKeyConstraint(['bedNo'], ['bed.bedNo'], ),
    sa.ForeignKeyConstraint(['doctor_ID'], ['medicalstaff.StaffID'], ),
    sa.ForeignKeyConstraint(['nurse_ID'], ['medicalstaff.StaffID'], ),
    sa.ForeignKeyConstraint(['patient_ID'], ['patient.patientID'], ),
    sa.PrimaryKeyConstraint('bedNo', 'patient_ID')
    )
    op.create_table('medicine',
    sa.Column('medicineID', sa.CHAR(length=3), nullable=False),
    sa.Column('name', sa.CHAR(length=20), nullable=True),
    sa.Column('company', sa.CHAR(length=20), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('warehouse_ID', sa.CHAR(length=2), nullable=True),
    sa.Column('inDate', sa.DATE(), nullable=True),
    sa.Column('expireDate', sa.DATE(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('description', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['warehouse_ID'], ['warehouse.warehouseID'], ),
    sa.PrimaryKeyConstraint('medicineID')
    )
    op.create_table('prescription_detail',
    sa.Column('prescriptionID', sa.CHAR(length=5), nullable=False),
    sa.Column('medicine_ID', sa.CHAR(length=3), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['medicine_ID'], ['medicine.medicineID'], ),
    sa.PrimaryKeyConstraint('prescriptionID', 'medicine_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prescription_detail')
    op.drop_table('medicine')
    op.drop_table('hospitalization')
    op.drop_table('bed')
    # ### end Alembic commands ###
